version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: pip
      path: another/package
  system_packages: true