num_experiments: 1
controller_name: ControllerCemGradientBharadhwaj
environment_name: CustomEnvironments/Pendulum
num_iterations: 300
render_for_humans: False
save_plots_to_file: True
debug: False
logging_level: DEBUG
seed_entropy: 1234

environments:
  CustomEnvironments/CartPoleContinuous:
    actuator_noise: [0.0] # stdev, can be set to 0.0

  CustomEnvironments/MountainCarContinuous:
    actuator_noise: [0.0] # stdev

  CustomEnvironments/Pendulum:
    actuator_noise: [0.5] # stdev

controllers:
  ControllerAdamResampler:
    controller_logging: True
    mpc_horizon: .5
    dt: 0.02
    cem_outer_it: 5
    cem_rollouts: 200
    cem_predictor_type: EulerTF
    cem_stdev_min: 0.1
    cem_R: 1
    cem_ccrc_weight: 1
    cem_best_k: 5
    cem_LR: 0.1
    grad_max: 1
    grad_alpha: 0.05
    grad_beta_1: 0.9
    grad_beta_2: 0.999
    grad_epsilon: 1.0e-7
    cem_initial_action_variance: 0.5
    resamp_every: 1
    do_warmup: True

  ControllerCem:
    controller_logging: True
    mpc_horizon: 0.5
    dt: 0.02
    cem_outer_it: 5
    cem_rollouts: 200
    cem_predictor_type: EulerTF
    cem_stdev_min: 0.1
    cem_R: 1
    cem_ccrc_weight: 1
    cem_best_k: 5
    cem_LR: 0.1
    cem_initial_action_variance: 0.5

  ControllerCemGradient:
    controller_logging: True
    mpc_horizon: .5
    dt: 0.02
    cem_outer_it: 5
    cem_rollouts: 200
    cem_predictor_type: EulerTF
    cem_stdev_min: 0.1
    cem_R: 1
    cem_ccrc_weight: 1
    cem_best_k: 5
    cem_LR: 0.1
    grad_max: 1
    grad_alpha: 0.05
    cem_initial_action_variance: 0.5
  
  ControllerCemGradientBharadhwaj:
    controller_logging: True
    cem_rollouts: 30
    mpc_horizon: .5
    dt: 0.02
    cem_outer_it: 20
    cem_best_k: 5
    grad_max: 1
    grad_learning_rate: 0.1
    grad_sgd_momentum: 0.0
    grad_epsilon: 1.0e-6


