1_data_generation:
  controller_names:
  - controller_cem_tf
  # - controller_cem_naive_grad_tf
  - controller_dist_adam_resamp2
  # - controller_mppi_tf
  - controller_cem_grad_bharadhwaj
  # - controller_gradient_tf
  debug: false
  environment_names: CustomEnvironments/DubinsCar-v0
  logging_level: DEBUG
  num_experiments: 1
  num_iterations: 100
  render_for_humans: false
  save_plots_to_file: true
  seed_entropy: 94172
  split:
  - 0.6
  - 0.2
  use_gpu: true
2_environments:
  CustomEnvironments/CartPoleContinuous-v0:
    actuator_noise:
    - 0.0
  CustomEnvironments/MountainCarContinuous-v0:
    actuator_noise:
    - 0.0
  CustomEnvironments/Pendulum-v0:
    actuator_noise:
    - 0.2
  CustomEnvironments/DubinsCar-v0:
    actuator_noise:
    - 0.2
    - 0.2
    target_point: [0.9, 0.0, 0.0]
    obstacle_positions: null
    # - [0.0, 0.0, 0.2]
  CustomEnvironments/HalfCheetahBatched-v0:
    actuator_noise:
    - 0.0
    forward_reward_weight: 1.0
    ctrl_cost_weight: 0.1
    reset_noise_scale: 0.1
    exclude_current_positions_from_observation: true
  CustomEnvironments/AcrobotBatched-v0:
    actuator_noise:
    - 0.0
  CustomEnvironments/CartPoleSimulator-v0:
    actuator_noise:
    - 0.0
    dt: 0.02
    mode: stabilization
    cart_length: 4.4e-2
    usable_track_length: 44.0e-2
    u_max: 2.62
3_predictors:
  PredictorGaussianError:
    prediction_error_stdev: 0.1
4_controllers:
  controller_logging: true
  dt: 0.02
  mpc_horizon: 1.0

######################################################################################

  # Control_Toolkit Controllers
  controller_cem_grad_bharadhwaj:
    CEM_NET_NAME: GRU-3IN-32H1-32H2-2OUT-0
    cem_LR: 0.05
    cem_R: 1
    cem_best_k: 4
    cem_outer_it: 5
    cem_rollouts: 40
    cem_initial_action_stdev: 0.5
    cem_stdev_min: 0.2
    gradmax_clip: 5
    predictor_intermediate_steps: 10
    predictor_name: predictor_ODE_tf
  controller_gradient_tf:
    CEM_NET_NAME: GRU-3IN-32H1-32H2-2OUT-0
    learning_rate: 0.05
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    adam_epsilon: 1.0e-07
    gradient_steps: 5
    mpc_rollouts: 40
    initial_action_stdev: 0.5
    gradmax_clip: 5
    predictor_intermediate_steps: 10
    predictor_name: predictor_ODE_tf
  controller_cem_naive_grad_tf:
    CEM_NET_NAME: GRU-3IN-32H1-32H2-2OUT-0
    cem_LR: 0.05
    cem_R: 1
    cem_best_k: 4
    cem_ccrc_weight: 1
    cem_outer_it: 5
    cem_rollouts: 40
    cem_initial_action_stdev: 0.5
    cem_stdev_min: 0.2
    gradmax_clip: 5
    predictor_intermediate_steps: 10
    predictor_name: predictor_ODE_tf
  controller_cem_tf:
    CEM_NET_NAME: GRU-3IN-32H1-32H2-2OUT-0
    cem_R: 1
    cem_best_k: 4
    cem_ccrc_weight: 1
    cem_outer_it: 5
    cem_rollouts: 40
    cem_stdev_min: 0.2
    predictor_intermediate_steps: 10
    predictor_name: predictor_ODE_tf
  controller_dist_adam_resamp2:
    NET_NAME: GRU-6IN-32H1-32H2-5OUT-0
    SAMPLING_TYPE: None
    adam_beta_1: 0.9
    adam_beta_2: 0.999
    adam_epsilon: 1.0e-07
    cem_LR: 0.05
    gradmax_clip: 5
    rtol: 1.0e-3
    interpolation_step: 10
    num_rollouts: 10
    opt_keep_k: 2
    outer_its: 20
    predictor_intermediate_steps: 10
    predictor_name: predictor_ODE_tf
    resamp_per: 5
    sample_stdev: 0.5
    warmup: false
  controller_mppi_optimize:
    GAMMA: 1.0
    LBD: 100.0
    NET_NAME: GRU-6IN-32H1-32H2-5OUT-0
    NU: 1000.0
    R: 1.0
    SAMPLING_TYPE: interpolated
    SQRTRHOINV: 0.02
    adam_beta_1: 0.4
    adam_beta_2: 0.8
    adam_epsilon: 1.0e-07
    cc_weight: 1.0
    gradmax_clip: 1000
    mppi_LR: 0.02
    num_rollouts: 400
    optim_steps: 10
    predictor_intermediate_steps: 10
    predictor_name: predictor_ODE_tf
  controller_mppi_tf:
    GAMMA: 1.0
    GP_NAME: SGP_30
    LBD: 100.0
    LOGGING: false
    NET_NAME: GRU-6IN-32H1-32H2-5OUT-0
    NU: 1000.0
    R: 1.0
    SAMPLING_TYPE: None
    SQRTRHOINV: 0.5
    WASH_OUT_LEN: 100
    cc_weight: 1.0
    ccrc_weight: 1.0
    control_noise: 0.0
    cost_noise: 0.0
    dd_weight: 120.0
    ekc_weight: 5.0
    ekp_weight: 0.01
    ep_weight: 50000.0
    num_rollouts: 1000
    predictor_intermediate_steps: 10
    predictor_name: predictor_ODE_tf
    update_every: 1
  controller_mppi_var:
    GAMMA: 1.0
    LBD_mc: 10.0
    LR: 0.01
    NET_NAME: GRU-6IN-32H1-32H2-5OUT-0
    NU_mc: 20.0
    R: 1.0
    SAMPLING_TYPE: interpolated
    SQRTRHOINV_mc: 0.002
    STDEV_max: 10
    STDEV_min: 0.1
    cc_weight: 1.0
    interpolation_step: 10
    max_grad_norm: 100000
    num_rollouts: 400
    predictor_intermediate_steps: 10
    predictor_name: predictor_ODE_tf

######################################################################################

  # Reimplemented Gym Controllers
  ControllerAdamResampler:
    cem_LR: 0.1
    cem_R: 1
    cem_best_k: 5
    cem_ccrc_weight: 1
    cem_initial_action_variance: 0.5
    cem_outer_it: 30
    cem_rollouts: 30
    cem_stdev_min: 0.1
    do_warmup: true
    grad_alpha: 0.05
    grad_beta_1: 0.9
    grad_beta_2: 0.999
    grad_epsilon: 1.0e-07
    grad_max: 1
    predictor_name: PredictorEuler
    resamp_every: 1
  ControllerCem:
    cem_LR: 0.1
    cem_R: 1
    cem_best_k: 5
    cem_ccrc_weight: 1
    cem_initial_action_variance: 0.5
    cem_outer_it: 5
    cem_rollouts: 200
    cem_stdev_min: 0.1
    predictor_name: PredictorEuler
  ControllerCemGradient:
    cem_LR: 0.1
    cem_R: 1
    cem_best_k: 5
    cem_ccrc_weight: 1
    cem_initial_action_variance: 0.5
    cem_outer_it: 5
    cem_rollouts: 200
    cem_stdev_min: 0.1
    grad_alpha: 0.05
    grad_max: 1
    predictor_name: PredictorEuler
  ControllerCemGradientBharadhwaj:
    cem_best_k: 5
    cem_outer_it: 20
    cem_rollouts: 30
    grad_epsilon: 1.0e-06
    grad_learning_rate: 0.1
    grad_max: 1
    grad_sgd_momentum: 0.0
    predictor_name: PredictorEuler
  ControllerMPPIGradient:
    cem_LR: 0.1
    cem_R: 1
    cem_best_k: 5
    cem_ccrc_weight: 1
    cem_initial_action_variance: 0.5
    cem_outer_it: 10
    cem_rollouts: 10
    cem_stdev_min: 0.05
    do_warmup: true
    grad_alpha: 0.05
    grad_beta_1: 0.9
    grad_beta_2: 0.999
    grad_epsilon: 1.0e-07
    grad_max: 5
    mppi_lambda: 0.1
    predictor_name: PredictorEuler
    resamp_every: 1
