### ------------------------------------------------------- ###
### Add any flags here that you'd like to use to overwrite the defaults
### The syntax is:
### custom_config_overwrites:
###   <<config_name without ".yml" suffix>>:
###     key:
###       key: <<optionally: a value>>
###       ...
### Example:
### custom_config_overwrites:
###   config_optimizers:
###     cem-tf:
###       cem_best_k: 4
###   config_controllers:
###     mpc:
###       controller_logging:
### Any parameter specified here can also be overwritten as flag in bash.
### Example: `guild run controller_mpc:run_control custom_config_overwrites.config_optimizers.cem-tf.cem_best_k='[1,4,16]'`
###
custom_config_overwrites:
  config_controllers:
    mpc:
      optimizer: cem-tf
      controller_logging:
  config_predictors:
    predictors:
      ODE_TF_default:
        model_name: overwritten
      GP_default:
        model_name: overwritten


### ------------------------------------------------------- ###

### The following flags are required. Modify them as needed: ###
### Alternatively, you can pass values as flags in bash      ###
controller_name: controller_mpc
environment_name: MountainCarContinuous-v0

### ------------------------------------------------------- ###

1_data_generation:
  controller_names:
  - controller_mpc
  optimizer_names:
  # - optimizer_cem_tf
  # - optimizer_mppi_tf
  # - optimizer_mppi_var_tf
  # - optimizer_mppi_optimize_tf
  # - optimizer_cem_grad_bharadhwaj_tf
  # - optimizer_gradient_tf
  # - optimizer_random_action_tf
  - optimizer_rpgd_tf
  - optimizer_rpgd_me_tf
  # - optimizer_rpgd_ml_tf
  environment_names:
  - MountainCarContinuous-v0
  - CartPoleSimulator-v0
  # - DubinsCar-v0
  # - Acrobot-v0
  # - Pendulum-v0
  # - CartPoleContinuous-v0
  # - BipedalWalkerBatched-v0
  # - ObstacleAvoidance-v0
  debug: false  # false to use tf.compile
  use_jit_compilation: false  # false for reproducibility
  use_gpu: false
  logging_level: ERROR
  num_experiments: 10
  num_iterations: 200
  render_for_humans: false
  save_plots_to_file: false
  seed_entropy: 49604
  split:
  - 0.6
  - 0.2