num_experiments: 1
controller_name: ControllerMPPIGradient
environment_name: CustomEnvironments/MountainCarContinuous
num_iterations: 150
render_for_humans: False
save_plots_to_file: True
debug: False  # Debugging mode turns off compilation/graph mode
logging_level: DEBUG
seed_entropy: 1234

environments:
  CustomEnvironments/CartPoleContinuous:
    actuator_noise: [0.0] # stdev, can be set to 0.0

  CustomEnvironments/MountainCarContinuous:
    actuator_noise: [0.0] # stdev

  CustomEnvironments/Pendulum:
    actuator_noise: [0.5] # stdev

predictors:
  PredictorGaussianError:
    prediction_error_stdev: 0.1

controllers:
  controller_logging: True
  mpc_horizon: .5
  dt: 0.02
  predictor: PredictorEuler

  ControllerAdamResampler:
    cem_outer_it: 30
    cem_rollouts: 30
    cem_stdev_min: 0.1
    cem_R: 1
    cem_ccrc_weight: 1
    cem_best_k: 5
    cem_LR: 0.1
    grad_max: 1
    grad_alpha: 0.05
    grad_beta_1: 0.9
    grad_beta_2: 0.999
    grad_epsilon: 1.0e-7
    cem_initial_action_variance: 0.5
    resamp_every: 1
    do_warmup: True
  
  ControllerMPPIGradient:
    cem_outer_it: 10
    cem_rollouts: 10
    cem_stdev_min: 0.05
    cem_R: 1
    cem_ccrc_weight: 1
    cem_best_k: 5
    cem_LR: 0.1
    grad_max: 5
    grad_alpha: 0.05
    grad_beta_1: 0.9
    grad_beta_2: 0.999
    grad_epsilon: 1.0e-7
    cem_initial_action_variance: 0.5
    resamp_every: 1
    do_warmup: True
    mppi_lambda: 0.1

  ControllerCem:
    cem_outer_it: 5
    cem_rollouts: 200
    cem_stdev_min: 0.1
    cem_R: 1
    cem_ccrc_weight: 1
    cem_best_k: 5
    cem_LR: 0.1
    cem_initial_action_variance: 0.5

  ControllerCemGradient:
    cem_outer_it: 5
    cem_rollouts: 200
    cem_stdev_min: 0.1
    cem_R: 1
    cem_ccrc_weight: 1
    cem_best_k: 5
    cem_LR: 0.1
    grad_max: 1
    grad_alpha: 0.05
    cem_initial_action_variance: 0.5
  
  ControllerCemGradientBharadhwaj:
    cem_rollouts: 30
    cem_outer_it: 20
    cem_best_k: 5
    grad_max: 1
    grad_learning_rate: 0.1
    grad_sgd_momentum: 0.0
    grad_epsilon: 1.0e-6


