### ------------------------------------------------------- ###
### Add any flags here that you'd like to use to overwrite the defaults
### The syntax is:
### custom_config_overwrites:
###   <<config_name without ".yml" suffix>>:
###     key:
###       key: <<optionally: a value>>
###       ...
### Example:
### custom_config_overwrites:
###   config_optimizers:
###     cem-tf:
###       cem_best_k: 4
###   config_controllers:
###     mpc:
###       controller_logging:
### Any parameter specified here can also be overwritten as flag in bash.
### Example: `guild run controller_mpc:run_control custom_config_overwrites.config_optimizers.cem-tf.cem_best_k='[1,4,16]'`
###
custom_config_overwrites:
  config_controllers:
    mpc:
      optimizer: rpgd-tf


### ------------------------------------------------------- ###

### The following flags are required. Modify them as needed: ###
### Alternatively, you can pass values as flags in bash      ###
controller_name: controller_mpc
environment_name: MountainCarContinuous-v0

### ------------------------------------------------------- ###

debug: false  # false to use tf.compile
use_jit_compilation: false  # false for reproducibility
use_gpu: false
logging_level: DEBUG
num_experiments: 5
num_iterations: 200
render_for_humans: false
save_plots_to_file: true
seed_entropy: 49604
split:
- 0.6
- 0.2