mpc:
  optimizer: gradient-tf
  predictor_specification: ODE_TF
  cost_function_specification: discounted_horizon
#  cost_function_specification: default
  computation_library: tensorflow
  controller_logging: false
