mpc:
  optimizer: nlp-forces
#  optimizer: rpgd-tf
#  optimizer: mppi
  predictor_specification: ODE_TF
  cost_function_specification: default
  computation_library: tensorflow
  controller_logging: true
