cost_function_name_default: default
# Default value is used if controller does not specify a cost_function_specification (leave empty)
# Cost functions are grouped by environment name in a folder within Control_Toolkit_ASF.Cost_Functions
# Check config.yml to learn more on how cost_functions are selected

GymEnvironment:
  default:


acrobot_batched:
  default:
    angle_weight: 1.0
    angleD_weight: 0.01
  discounted_horizon:
    angle1_weight: 1.0
    angle2_weight: 0.5
    angleD1_weight: 0.02
    angleD2_weight: 0.01
    discount_factor: 0.95
cartpole_simulator_batched:
  default:
    angle_weight: 1.0
    position_weight: 1.0
continuous_cartpole_batched:
  default:
    angle_weight: 100.0
    angleD_weight: 1.0
    position_weight: 1.0
    positionD_weight: 1.0
continuous_mountaincar_batched:
  default:
    altitude_weight: 1.0
    done_reward: 100.0
    control_penalty: 0.1
dubins_car_batched:
  default:
    goal_reward: 10.0
    quadratic_cost_weight: 0.125
    distance_to_target_weight: 0.1
    distance_to_obstacle_weight: 5.0
    out_of_bounds_penalty: 1.0
obstacle_avoidance_batched:
  default:
    goal_reward: 100.0
    distance_to_target_weight: 5.0
    distance_to_obstacle_weight: 5.0
    out_of_bounds_cost: 100.0
pendulum_batched:
  default:
    angle_weight: 1.0
    angleD_weight: 0.1
    control_weight: 0.001
lunar_lander_batched:
  default:
    pos_x_weight: 1.1
    pos_y_weight: 1.0
    vel_weight: 0.2
    angle_weight: 0.1
    vel_angle_weight: 0.0
    discount_factor: 0.98
armbot_batched:
  default:
  discounted_horizon:
    discount_factor: 1.0
    distance_factor: 50.0