testing:
  tests: [ 'Euler', 'EulerTF','GRU-3IN-32H1-32H2-2OUT-0' ]  # May be 'Euler', Euler-predictor, name of network or None = 'Dense-16H1-16H2'
  TEST_FILE: 'Experiment-0.csv'
  features: ['x_0', 'x_1']
  control_inputs: ['Q']   # Indicates which inputs to network are control_input, TODO: Not sure how it would work with multiple inputs
  PATH_TO_NN: './Output/Experiments/Experiment-8/Models/'  # Path where the neural network models are stored
  PATH_TO_TEST_FILE: './Output/Experiments/Experiment-8/Recordings/Test/'
  TEST_LEN: 'max'
  DECIMATION: 1
  MAX_HORIZON: 50  # Indicates prediction horizon for testing
  START_IDX: 0  # Indicates from which point data from test file should be taken
