testing:
  tests: [ 'Euler', 'EulerTF','GRU-5IN-8H1-8H2-4OUT-0' ]  # May be 'Euler', Euler-predictor, name of network or None = 'Dense-16H1-16H2'
  TEST_FILE: 'Experiment-0.csv'
  features: ['x_0', 'x_1', 'x_2', 'x_3']  # Depends on the environment dimensionality
  control_inputs: ['u_0']   # Indicates which inputs to network are control_input, TODO: Not sure how it would work with multiple inputs
  PATH_TO_NN: 'Output/Experiments/Experiment-1/Models/'  # Path where the neural network models are stored
  PATH_TO_TEST_FILE: 'Output/Experiments/Experiment-1/Recordings/Test/'
  TEST_LEN: 'max'
  DECIMATION: 1
  MAX_HORIZON: 20  # Indicates prediction horizon for testing
  START_IDX: 0  # Indicates from which point data from test file should be taken
